### ISSUE TITLE
Epic: Multiplatform build of vcell-solvers on GitHub CI

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell-solvers#25]
***base solvers***
- FV solver (non-PETSc)
- Smoldyn
- nonspatial Stochastic
- NFSim
- Moving Boundary Solver

***Hy3S solvers*** (needs Fortran reconciled with LLVM toolchain)
- Hybrid_EM
- Hybrid_MIL
- Hybrid_MIL_Adaptive

***Chombo solvers*** (difficult multi-step build)
- Chombo2D (without parallel)
- Chombo3D (without parallel)

### subtasks
- [x] #13 
- [ ] #16
- [ ] #17
- [x] #27
- [ ] build base solvers on Github for Macos platform
- [x] https://github.com/virtualcell/vcell/issues/1023
- [x] #26
- [ ] build **Hy3S solvers** on Github for **native Macos**
- [ ] build **Hy3S solvers** on Github for **Docker** 
- [ ] build **Hy3S solvers** on Github for **native Linux**
- [ ] build **Hy3S solvers** on Github for **native Windows**
- [ ] build **Chombo solvers** on Github for **native Macos**
- [ ] build **Chombo solvers** on Github for **Docker** 
- [ ] build **Chombo solvers** on Github for **native Linux**
- [ ] build **Chombo solvers** on Github for **native Windows**
