### ISSUE TITLE
Epic: solver unit tests

### ISSUE THREAD

**Issue by jcschaff** [virtualcell/vcell-solvers#29]
### Motivation
Test coverage of most VCell solvers rely on integration testing and end to end testing with the math testing framework.  However, solver unit tests would allow independent testing of solver components and provide a framework for debugging and extending the solvers.

### Completion Criteria
- all solvers should have at least one unit test where results are compared with a typical output.

### Tasks
- [ ] #24 
- [ ] https://github.com/virtualcell/vcell/issues/819. (Motivated Nonspatial Stochastic Unit Test)
- [ ] unit test for FiniteVolume solver (non-PETSc)
- [ ] unit test for Smoldyn solver
- [ ] unit test for NFSim
- [ ] unit test for Moving Boundary Solver
- [ ] unit test for Hy3S solvers (Hybrid_EM, Hybrid_MIL, Hybrid_MIL_Adaptive)
- [ ] unit test for Chombo2D solver
- [ ] unit test for Chombo3D solver
